apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  labels:
    app: todos-api
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todos-api
    spec:
      containers:
        - image: registry.example.com/root/todos-api/todos-api
          name: todos-api
          ports:
          - containerPort: 8081
          env:
          - name: JWT_SECRET
            value: myfancysecret
          - name: TODO_API_PORT
            value: "8082"
          - name: REDIS_HOST
            value: redis-queue
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_CHANNEL
            value: log_channel
          - name: ZIPKIN_URL
            value: http://zipkin:9411/api/v2/spans
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      schedulerName: default-scheduler
      imagePullSecrets:
      - name: dockerhub-image-pull-secret