apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  labels:
    app: log-message-processor
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: log-message-processor
    spec:
      containers:
        - image: registry.example.com/root/log-message-processor/log-message-processor
          name: log-message-processor
          ports:
          - containerPort: 8081
          env:
          - name: REDIS_HOST
            value: redis-queue
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_CHANNEL
            value: log_channel
          - name: ZIPKIN_URL
            value: http://zipkin:9411/api/v1/spans
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      schedulerName: default-scheduler
      imagePullSecrets:
      - name: dockerhub-image-pull-secret
