stages:
  - build
  - deploy
image: docker

variables:
  DOCKER_HOST: tcp://192.168.2.2:2375

build-job:
  stage: build
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - echo "Start build job"
    - docker build -f log-message-processor/Dockerfile -t registry.example.com/root/log-message-processor/log-message-processor:$CI_COMMIT_SHORT_SHA ./log-message-processor
    - docker push registry.example.com/root/log-message-processor/log-message-processor:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  image: nastja1/test:k8s-deploy
  script:
    - kubectl get pods -n micro
    - kubectl apply -f ./k8s -n micro 
